FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 as builder

# Install Rust and required packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl build-essential pkg-config libssl-dev && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    . $HOME/.cargo/env && \
    echo 'source $HOME/.cargo/env' >> ~/.bashrc

# Set path for Rust
ENV PATH="/root/.cargo/bin:${PATH}"

# Copy and build your Rust project
COPY ./soma_core /soma_core 
WORKDIR /home
COPY soma_desc/src ./src
COPY soma_desc/Cargo.toml ./Cargo.toml
RUN cargo build --release

# Runtime stage
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04 as runtime
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /home 
COPY --from=builder /home/target/release/soma_desc /home
CMD [ "/home/soma_desc", "--workers", "4" ]
